version: '3'
services:
  php-environment:
    container_name: php-apache-BSD-O-AUG23A
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db-BSD-O-AUG23A
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "9906:3306"
    volumes:
      - ./api/db/sommen.sql:/docker-entrypoint-initdb.d/sommen.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-BSD-O-AUG23A
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80